In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE, ADASYN
from sklearn.model_selection import GridSearchCV
import xgboost as xgb

In [ ]:
train = pd.read_csv('train/train.csv')
test = pd.read_csv('test/test.csv')

In [36]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14993 entries, 0 to 14992
Data columns (total 24 columns):
Type             14993 non-null int64
Name             14993 non-null object
Age              14993 non-null int64
Breed1           14993 non-null int64
Breed2           14993 non-null int64
Gender           14993 non-null int64
Color1           14993 non-null int64
Color2           14993 non-null int64
Color3           14993 non-null int64
MaturitySize     14993 non-null int64
FurLength        14993 non-null int64
Vaccinated       14993 non-null int64
Dewormed         14993 non-null int64
Sterilized       14993 non-null int64
Health           14993 non-null int64
Quantity         14993 non-null int64
Fee              14993 non-null int64
State            14993 non-null int64
RescuerID        14993 non-null object
VideoAmt         14993 non-null int64
Description      14993 non-null object
PetID            14993 non-null object
PhotoAmt         14993 non-null float64
AdoptionSpeed    14993 non-null int64
dtypes: float64(1), int64(19), object(4)
memory usage: 2.7+ MB

In [42]:
train.Color1.value_counts()

1    7427
2    3750
3     947
5     884
6     684
7     667
4     634
Name: Color1, dtype: int64

In [43]:
train.Color2.value_counts()

0    4471
7    3438
2    3313
5    1128
6    1063
4     870
3     710
Name: Color2, dtype: int64

In [44]:
train.Color3.value_counts()

0    10604
7     3221
5      417
6      378
4      198
3      175
Name: Color3, dtype: int64

In [ ]:
test.info()

In [ ]:
train.isna().sum()

In [ ]:
test.isna().sum()

In [ ]:
train.Name.fillna('None', inplace=True)
train.Description.fillna('None', inplace=True)
test.Name.fillna('None', inplace=True)
test.Description.fillna('None', inplace=True)

In [ ]:
labels = train.drop(['Name', 'RescuerID', 'Description', 'PetID', 'AdoptionSpeed'], axis=1)
test_labels = test.drop(['Name', 'RescuerID', 'Description', 'PetID'], axis=1)

In [ ]:
labels = pd.get_dummies(labels, columns = ['Breed1', 'Breed2', 'Gender', 'Color1', 'Color2', 'Color3',
                                 'MaturitySize', 'FurLength', 'Vaccinated', 'Dewormed', 'Sterilized', 'Health',
                                 'State', 'Type'
                                ])
test_labels = pd.get_dummies(test_labels, columns = ['Breed1', 'Breed2', 'Gender', 'Color1', 'Color2', 'Color3',
                                 'MaturitySize', 'FurLength', 'Vaccinated', 'Dewormed', 'Sterilized', 'Health',
                                 'State', 'Type'
                                ])

In [ ]:
labels.columns

In [ ]:
test_labels.columns

In [ ]:
diff_columns = set(labels.columns).difference(set(test_labels.columns))

In [ ]:
for i in diff_columns:
    test_labels[i] = test_labels.apply(lambda _: 0, axis=1)

In [ ]:
diff_columns2 = set(test_labels.columns).difference(set(labels.columns))

In [ ]:
for i in diff_columns2:
    labels[i] = labels.apply(lambda _: 0, axis=1)

In [ ]:
target = train['AdoptionSpeed']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(labels, target, test_size=0.2)

In [ ]:
clf = RandomForestClassifier()
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

In [ ]:
pred = pd.DataFrame(clf.predict(test_labels))

In [ ]:
pred.to_csv("submission.csv", index=True, index_label="PetID", header=["AdoptionSpeed"])

In [106]:
breeds = pd.read_csv('breed_labels.csv')

In [107]:
breeds

     BreedID  Type                          BreedName
0          1     1                      Affenpinscher
1          2     1                       Afghan Hound
2          3     1                   Airedale Terrier
3          4     1                             Akbash
4          5     1                              Akita
5          6     1                   Alaskan Malamute
6          7     1                   American Bulldog
7          8     1                American Eskimo Dog
8          9     1          American Hairless Terrier
9         10     1     American Staffordshire Terrier
10        11     1             American Water Spaniel
11        12     1                 Anatolian Shepherd
12        13     1             Appenzell Mountain Dog
13        14     1  Australian Cattle Dog/Blue Heeler
14        15     1                  Australian Kelpie
15        16     1                Australian Shepherd
16        17     1                 Australian Terrier
17        18     1                            Basenji
18        19     1                       Basset Hound
19        20     1                             Beagle
20        21     1                     Bearded Collie
21        22     1                          Beauceron
22        23     1                 Bedlington Terrier
23        24     1      Belgian Shepherd Dog Sheepdog
24        25     1         Belgian Shepherd Laekenois
25        26     1          Belgian Shepherd Malinois
26        27     1          Belgian Shepherd Tervuren
27        28     1               Bernese Mountain Dog
28        29     1                       Bichon Frise
29        30     1            Black and Tan Coonhound
..       ...   ...                                ...
277      277     2                               Manx
278      278     2                           Munchkin
279      279     2                           Nebelung
280      280     2               Norwegian Forest Cat
281      281     2                             Ocicat
282      282     2                 Oriental Long Hair
283      283     2                Oriental Short Hair
284      284     2                     Oriental Tabby
285      285     2                            Persian
286      286     2                          Pixie-Bob
287      287     2                         Ragamuffin
288      288     2                            Ragdoll
289      289     2                       Russian Blue
290      290     2                      Scottish Fold
291      291     2                        Selkirk Rex
292      292     2                            Siamese
293      293     2                           Siberian
294      294     2                             Silver
295      295     2                          Singapura
296      296     2                           Snowshoe
297      297     2                             Somali
298      298     2              Sphynx (hairless cat)
299      299     2                              Tabby
300      300     2                              Tiger
301      301     2                          Tonkinese
302      302     2                             Torbie
303      303     2                      Tortoiseshell
304      304     2                     Turkish Angora
305      305     2                        Turkish Van
306      306     2                             Tuxedo

[307 rows x 3 columns]

In [108]:
groups = pd.read_csv('dog_groups.csv')

In [109]:
groups

,Herding,Hound,Toy,Non-Sporting,Sporting,Terrier,Working,Misc,FSS
0,Australian Cattle Dog,Afghan Hound,Affenpinscher,American Eskimo Dog,American Water Spaniel,Airedale Terrier,Akita,Barbet,American Leopard Hound
1,Australian Shepherd,American English Coonhound,Brussels Griffon,Bichon Frise,Boykin Spaniel,American Hairless Terrier,Alaskan Malamute,Belgian Laekenois,Appenzeller Sennenhund
2,Bearded Collie,American Foxhound,Cavalier King Charles Spaniel,Boston Terrier,Brittany,American Staffordshire Terrier,Anatolian Shepherd Dog,Dogo Argentino,Australian Kelpie
3,Beauceron,Azawakh,Chihuahua,Bulldog,Chesapeake Bay Retriever,Australian Terrier,Bernese Mountain Dog,Dutch Shepherd,Australian Stumpy Tail Cattle Dog
4,Belgian Malinois,Basenji,Chinese Crested,Chinese Shar-Pei,Clumber Spaniel,Bedlington Terrier,Black Russian Terrier,Lancashire Heeler,Basset Fauve de Bretagne
5,Belgian Sheepdog,Basset Hound,English Toy Spaniel,Chow Chow,Cocker Spaniel,Border Terrier,Boerboel,Mudi,Bavarian Mountain Scent Hound
6,Belgian Tervuren,Beagle,Havanese,Coton De Tulear,Curly-Coated Retriever,Bull Terrier,Boxer,Norrbottenspets,Biewer Terrier
7,Bergamasco,Black and Tan Coonhound,Italian Greyhound,Dalmatian,English Cocker Spaniel,Cairn Terrier,Bullmastiff,Peruvian Inca Orchid,Bolognese
8,Berger Picard,Bloodhound,Japanese Chin,Finish Spitz,English Setter,Cesky Terrier,Cane Corso,Portuguese Podengo,Bracco Italiano
9,Border Collie,Bluetick Coonhound,Maltese,French Bulldog,English Springer Spaniel,Dandie Dinmont Terrier,Chinook,Russian Toy,Braque de Bourbonnais
10,Bouvier des Flandres,Borzoi,Manchester Terrier,Keeshond,Field Spaniel,Glen of Imaal Terrier,Doberman Pinscher,NaN,Braque Francais Pyrenean
11,Briard,Cirneco Dell’Etna,Miniature Pinscher,Lhasa Apso,Flat-Coated Retriever,Irish Terrier,Dogue de Bordeaux,NaN,Broholmer
12,Canaan Dog,Dachshund,Papillon,Lowchen,German Shorthaired Pointer,Kerry Blue Terrier,German Pinscher,NaN,Carolina Dog
13,Cardigan Welsh Corgi,English Foxhound,Pekingese,Norwegian Lundhund,German Wirehaired Pointer,Lakeland Terrier,Giant Schnauzer,NaN,Catahoula Leopard Dog
14,Collie,Grand Basset Griffon Vendeen,Pomeranian,Poodle,Golden Retriever,Manchester Terrier,Great Dane,NaN,Caucasian Shepherd Dog
15,Entlebucher Moutain Dog,Greyhound,Poodle (Toy),Schipperke,Gordon Setter,Miniature Bull Terrier,Great Pyrenees,NaN,Central Asian Shepherd Dog
16,Finnish Lapphund,Harrier,Pug,Shiba Inu,Irish Red and White Setter,Miniature Schnauzer,Greater Swiss Mountain Dog,NaN,Croatian Sheepdog
17,German Shepherd Dog,Ibizan Hound,Shih Tzu,Tibetan Spaniel,Irish Setter,Norfolk Terrier,Komondor,NaN,Czechoslovakian Vlack
18,Icelandic Sheepdog,Irish Wolfhound,Silky Terrier,Tibetan Terrier,Irish Water Spaniel,Norwich Terrier,Kuvasz,NaN,Danish-Swedish Farmdog
19,Miniature American Shepherd,Norwegian Elkhound,Toy Fox Terrier,Xoloitzcuintli,Labrador Retriever,Parson Russell Terrier,Leonberger,NaN,Deutscher Wachtelhund
20,Norwegian Buhund,Otterhound,Yorkshire Terrier,NaN,Lagotto Romagnolo,Rat Terrier,Mastiff,NaN,Drentsche Patrijshond
21,Old English Sheepdog,Petit Basset Griffon Vendeen,NaN,NaN,Nederlandse Kooikerhondje,Russell Terrier,Neapolitan Mastiff,NaN,Drever
22,Pembroke Welsh Corgi,Pharaoh Hound,NaN,NaN,Nova Scotia Duck Tolling Retriever,Scottish Terrier,Newfoundland,NaN,Estrela Mountain Dog
23,Polish Lowland Sheepdog,Plott,NaN,NaN,Pointer,Sealyham Terrier,Portuguese Water Dog,NaN,Eurasier
24,Puli,Portuguese Podengo Pequeno,NaN,NaN,Spinone Italiano,Skye Terrier,Rottweiler,NaN,French Spaniel
25,Pumi,Redbone Coonhound,NaN,NaN,Sussex Spaniel,Smooth Fox Terrier,Samoyed,NaN,German Longhaired Pointer
26,Pyrenean Shepherd,Rhodesian Ridgeback,NaN,NaN,Vizsla,Soft Coated Wheaten Terrier,Siberian Husky,NaN,German Spitz
27,Shetland Sheepdog,Saluki,NaN,NaN,Weimaraner,Staffordshire Bull Terrier,Standard Schnauzer,NaN,Hamiltonstovare
28,Spanish Water Dog,Scottish Deerhound,NaN,NaN,Welsh Springer Spaniel,Welsh Terrier,Tibetan Mastiff,NaN,Hanoverian Scenthound
29,Swedish Vallhund,Sloughi,NaN,NaN,Wirehaired Pointing Griffon,West Highland White Terrier,St. Bernard,NaN,Hokkaido
...,...,...,...,...,...,...,...,...,...
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lapponian Herder
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mountain Cur
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Perro de Presa Canario
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Porcelaine
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Portuguese Pointer
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Portuguese Sheepdog
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pudelpointer
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pyrenean Mastiff
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rafeiro de Alentejo
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Romanian Mioritic Shepherd Dog
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Russian Tsvetnaya Bolonka
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Schapendoes
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Segugio Italiano
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Shikoku
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Slovakian Wirehaired Pointer
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Slovensky Cuvac
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Slovensky Kopov
54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Small Musterlander Pointer
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spanish Mastiff
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stabyhoun
57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Swedish Lapphund
58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Taiwan Dog
59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Teddy Roosevelt Terrier
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Thai Ridgeback
61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tornjak
62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tosa
63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Transylvanian Hound
64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Treeing Tennessee Brindle
65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Working Kelpie
66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yakutian Laika

In [110]:
breeds['Group'] = breeds.apply(lambda _: 'i', axis=1)

In [111]:
dogs = breeds[breeds['Type'] == 1].copy()

In [112]:
for index, row in dogs.iterrows():
    for j in groups.columns:
        for h in groups[j]:
            if row['BreedName'] == h:
                dogs.set_value(index, 'Group', j)

C:\Users\sparr\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  """

In [113]:
dogs['Group'].value_counts()

i               88
Working         25
Hound           24
Terrier         22
Sporting        22
Toy             17
Herding         15
Non-Sporting    14
FSS             10
Misc             4
Name: Group, dtype: int64

In [114]:
dogs[dogs['Group'] == 'i']

     BreedID  Type                                 BreedName Group
3          4     1                                    Akbash     i
6          7     1                          American Bulldog     i
11        12     1                        Anatolian Shepherd     i
12        13     1                    Appenzell Mountain Dog     i
13        14     1         Australian Cattle Dog/Blue Heeler     i
23        24     1             Belgian Shepherd Dog Sheepdog     i
24        25     1                Belgian Shepherd Laekenois     i
25        26     1                 Belgian Shepherd Malinois     i
26        27     1                 Belgian Shepherd Tervuren     i
30        31     1                  Black Labrador Retriever     i
31        32     1                           Black Mouth Cur     i
34        35     1                                 Blue Lacy     i
42        43     1                      Bouvier des Flanders     i
46        47     1                          Brittany Spaniel     i
52        53     1                        Cane Corso Mastiff     i
55        56     1                                Cattle Dog     i
56        57     1  Caucasian Sheepdog (Caucasian Ovtcharka)     i
60        61     1                       Chinese Crested Dog     i
61        62     1                           Chinese Foo Dog     i
63        64     1              Chocolate Labrador Retriever     i
65        66     1                         Cirneco dell'Etna     i
67        68     1                                  Cockapoo     i
70        71     1                                 Coonhound     i
71        72     1                                     Corgi     i
72        73     1                           Coton de Tulear     i
76        77     1                     Dandi Dinmont Terrier     i
81        82     1                           English Bulldog     i
83        84     1                         English Coonhound     i
84        85     1                           English Pointer     i
86        87     1                          English Shepherd     i
..       ...   ...                                       ...   ...
172      173     1                          Pit Bull Terrier     i
173      174     1                               Plott Hound     i
174      175     1                        Podengo Portugueso     i
180      181     1                             Presa Canario     i
186      187     1                                 Retriever     i
189      190     1                             Saint Bernard     i
192      193     1                               Sarplaninac     i
194      195     1                                 Schnauzer     i
196      197     1                  Scottish Terrier Scottie     i
198      199     1                                    Setter     i
199      200     1                                  Shar Pei     i
200      201     1                                 Sheep Dog     i
201      202     1                                  Shepherd     i
202      203     1                 Shetland Sheepdog Sheltie     i
210      211     1                   South Russian Ovtcharka     i
211      212     1                                   Spaniel     i
212      213     1                                     Spitz     i
214      215     1                           Standard Poodle     i
217      218     1                                   Terrier     i
222      223     1                                  Tosa Inu     i
227      228     1                               Welsh Corgi     i
230      231     1        West Highland White Terrier Westie     i
231      232     1                           Wheaten Terrier     i
233      234     1                     White German Shepherd     i
235      236     1              Wire-haired Pointing Griffon     i
236      237     1                        Wirehaired Terrier     i
237      238     1           Xoloitzcuintle/Mexican Hairless     i
238      239     1                 Yellow Labrador Retriever     i
239      240     1                  Yorkshire Terrier Yorkie     i
240      307     1                               Mixed Breed     i

[88 rows x 4 columns]

In [126]:
for index, row in dogs[dogs['Group']=='i'].iterrows():
    if 'TERRIER' in row['BreedName'].upper():
        dogs.set_value(index, 'Group', 'Terrier')
    if 'BULLDOG' in row['BreedName'].upper():
        dogs.set_value(index, 'Group', 'Non-Sporting')
    if 'POODLE' in row['BreedName'].upper():
        dogs.set_value(index, 'Group', 'Non-Sporting')
    if 'CORGI' in row['BreedName'].upper():
        dogs.set_value(index, 'Group', 'Herding')
    if 'RETRIEVER' in row['BreedName'].upper():
        dogs.set_value(index, 'Group', 'Sporting')
    if 'SCHNAUZER' in row['BreedName'].upper():
        dogs.set_value(index, 'Group', 'Working')

C:\Users\sparr\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  del sys.path[0]

In [127]:
dogs[dogs['Group'] == 'i']

     BreedID  Type                                 BreedName Group
3          4     1                                    Akbash     i
11        12     1                        Anatolian Shepherd     i
12        13     1                    Appenzell Mountain Dog     i
13        14     1         Australian Cattle Dog/Blue Heeler     i
23        24     1             Belgian Shepherd Dog Sheepdog     i
24        25     1                Belgian Shepherd Laekenois     i
25        26     1                 Belgian Shepherd Malinois     i
26        27     1                 Belgian Shepherd Tervuren     i
31        32     1                           Black Mouth Cur     i
34        35     1                                 Blue Lacy     i
42        43     1                      Bouvier des Flanders     i
46        47     1                          Brittany Spaniel     i
52        53     1                        Cane Corso Mastiff     i
55        56     1                                Cattle Dog     i
56        57     1  Caucasian Sheepdog (Caucasian Ovtcharka)     i
60        61     1                       Chinese Crested Dog     i
61        62     1                           Chinese Foo Dog     i
65        66     1                         Cirneco dell'Etna     i
67        68     1                                  Cockapoo     i
70        71     1                                 Coonhound     i
72        73     1                           Coton de Tulear     i
83        84     1                         English Coonhound     i
84        85     1                           English Pointer     i
86        87     1                          English Shepherd     i
89        90     1                               Entlebucher     i
90        91     1                                Eskimo Dog     i
91        92     1                                     Feist     i
93        94     1                           Fila Brasileiro     i
95        96     1                             Finnish Spitz     i
98        99     1                                  Foxhound     i
..       ...   ...                                       ...   ...
126      127     1                           Italian Spinone     i
131      132     1                                   Kai Dog     i
135      136     1                                     Kishu     i
136      137     1                                  Klee Kai     i
139      140     1                                   Kyi Leo     i
148      149     1                          Maremma Sheepdog     i
150      151     1                                     McNab     i
153      154     1                              Mountain Dog     i
154      155     1                             Munsterlander     i
156      157     1                    New Guinea Singing Dog     i
157      158     1                          Newfoundland Dog     i
161      162     1                       Norwegian Lundehund     i
173      174     1                               Plott Hound     i
174      175     1                        Podengo Portugueso     i
180      181     1                             Presa Canario     i
189      190     1                             Saint Bernard     i
192      193     1                               Sarplaninac     i
198      199     1                                    Setter     i
199      200     1                                  Shar Pei     i
200      201     1                                 Sheep Dog     i
201      202     1                                  Shepherd     i
202      203     1                 Shetland Sheepdog Sheltie     i
210      211     1                   South Russian Ovtcharka     i
211      212     1                                   Spaniel     i
212      213     1                                     Spitz     i
222      223     1                                  Tosa Inu     i
233      234     1                     White German Shepherd     i
235      236     1              Wire-haired Pointing Griffon     i
237      238     1           Xoloitzcuintle/Mexican Hairless     i
240      307     1                               Mixed Breed     i

[64 rows x 4 columns]

In [129]:
dogs.to_csv('dog_breeds.csv')

In [130]:
dogs = pd.read_csv('dog_breeds.csv')

In [136]:
joined = train.join(dogs, lsuffix='Breed1', rsuffix='BreedID')

In [139]:
joined[joined['TypeBreed1'] == 1]['Group'].value_counts()

Working         23
Hound           21
Sporting        20
Terrier         20
Herding         16
Non-Sporting    12
Toy             11
FSS              9
Misc             5
Hunting          3
Name: Group, dtype: int64

In [140]:
joined.head()

,TypeBreed1,Name,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,...,VideoAmt,Description,PetID,PhotoAmt,AdoptionSpeed,Unnamed: 0,BreedID,TypeBreedID,BreedName,Group
0,2,Nibble,3,299,0,1,1,7,0,1,...,0,Nibble is a 3+ month old ball of cuteness. He ...,86e1089a3,1.0,2,0.0,1.0,1.0,Affenpinscher,Toy
1,2,No Name Yet,1,265,0,1,1,2,0,2,...,0,I just found it alone yesterday near my apartm...,6296e909a,2.0,0,1.0,2.0,1.0,Afghan Hound,Hound
2,1,Brisco,1,307,0,1,2,7,0,2,...,0,Their pregnant mother was dumped by her irresp...,3422e4906,7.0,3,2.0,3.0,1.0,Airedale Terrier,Terrier
3,1,Miko,4,307,0,2,1,2,0,2,...,0,"Good guard dog, very alert, active, obedience ...",5842f1ff5,8.0,2,3.0,4.0,1.0,Akbash,Working
4,1,Hunter,1,307,0,1,1,0,0,2,...,0,This handsome yet cute boy is up for adoption....,850a43f90,3.0,2,4.0,5.0,1.0,Akita,Working

In [146]:
joined = joined.apply(lambda x: 'Misc' if x == None)

SyntaxError: invalid syntax (<ipython-input-146-dd7fa922b0d4>, line 1)

In [147]:
joined.isna().sum()

TypeBreed1           0
Name                 0
Age                  0
Breed1               0
Breed2               0
Gender               0
Color1               0
Color2               0
Color3               0
MaturitySize         0
FurLength            0
Vaccinated           0
Dewormed             0
Sterilized           0
Health               0
Quantity             0
Fee                  0
State                0
RescuerID            0
VideoAmt             0
Description          0
PetID                0
PhotoAmt             0
AdoptionSpeed        0
Unnamed: 0       14752
BreedID          14752
TypeBreedID      14752
BreedName        14752
Group            14752
dtype: int64

In [148]:
train.columns

Index(['Type', 'Name', 'Age', 'Breed1', 'Breed2', 'Gender', 'Color1', 'Color2',
       'Color3', 'MaturitySize', 'FurLength', 'Vaccinated', 'Dewormed',
       'Sterilized', 'Health', 'Quantity', 'Fee', 'State', 'RescuerID',
       'VideoAmt', 'Description', 'PetID', 'PhotoAmt', 'AdoptionSpeed'],
      dtype='object')

In [149]:
train['Breed1']

0        299
1        265
2        307
3        307
4        307
5        266
6        264
7        307
8        265
9        265
10       307
11       264
12       307
13       265
14       307
15       218
16       266
17       307
18       307
19       266
20       307
21       307
22       114
23       307
24       266
25       285
26       285
27       266
28       189
29       266
        ...
14963    276
14964    265
14965    266
14966    265
14967    265
14968    266
14969    266
14970    307
14971    265
14972    266
14973    307
14974    307
14975    307
14976    264
14977    254
14978    307
14979    307
14980    307
14981    307
14982    266
14983    307
14984    307
14985    179
14986    266
14987    195
14988    266
14989    265
14990    265
14991    266
14992    307
Name: Breed1, Length: 14993, dtype: int64

In [154]:
train['Group'] = breeds.apply(lambda _: 'i', axis=1)
              
for index, row in train.iterrows():
    for i, r in dogs.iterrows():
        if row['Breed1'] == r['BreedID']:
            train.set_value(index, 'Group', r['BreedID'])

C:\Users\sparr\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

In [ ]:
dogs.head()